name = "ai-realtime-translator-worker"
main = "src/index.ts"
compatibility_date = "2024-08-21"

[dev]
port = 8787

[vars]
# 本番のフロントドメイン（Pages など）を設定してください（カンマ区切り可）
ALLOWED_ORIGINS = "https://ai-realtime-translator.fukata.dev"
# 許可メール（Access と二重で制限する場合に設定。カンマ区切り）
ALLOWED_EMAILS = "tatsuya.fukata@gmail.com"
# 本番では必ず Access バイパスを無効化
DEV_BYPASS_ACCESS = "false"
